spring.application.name=Free-CRM-Java

# C# API connection settings
api.base-url=http://localhost:5000/api

# Database Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CRM-LTE-FS;encrypt=true;trustServerCertificate=true
spring.datasource.username=irina
spring.datasource.password=root

# JDBC Driver Class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver